---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-plex
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  dependsOn:
  - name: cluster-apps-cert-manager
  - name: cluster-apps-kube-prometheus-stack
  path: ./cluster/apps/default/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: plex
    namespace: default
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
    - kind: ConfigMap
      name: cluster-settings
