---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gateway-api
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/gateway-api/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gateway-api-resources
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-apps-gateway-api
  - name: cluster-apps-cilium
  path: ./cluster/apps/networking/gateway-api/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
