---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backends.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_httproutefilters.yaml
- https://raw.githubusercontent.com/envoyproxy/gateway/v1.7.2/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
