---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.5.0
  ignore: |
    # exclude all
    /*
    # include Gateway API CRDs
    !/config
    /config/*
    !/config/crd
    /config/crd/*
    !/config/crd/kustomization.yaml
    !/config/crd/standard
    !/config/crd/standard/**
