---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: cilium
    namespace: kube-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
      optional: false
    - kind: ConfigMap
      name: cluster-settings
      optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium
  path: ./cluster/apps/networking/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
      optional: false
    - kind: ConfigMap
      name: cluster-settings
      optional: false
