---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: networking
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      envoyGateway:
        enabled: true
      gatewayAPI:
        enabled: false
    deployment:
      replicas: 1
    service:
      type: ClusterIP
