---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: docker.io/plexinc/pms-docker
              tag: latest
            env:
              VERSION: public
              UMASK_SET: "022"
              # visit https://plex.tv/claim
              PLEX_CLAIM: ${PLEX_CLAIM}
              PLEX_UID: "1000"
              PLEX_GID: "100"
              PLEX_ADVERTISE_URL: "https://plex.${CLUSTER_DOMAIN},http://{PLEX}:32400"
            securityContext:
              privileged: true
    service:
      app:
        primary: true
        controller: plex
        ports:
          http:
            port: 32400
        type: LoadBalancer
        loadBalancerIP: "${PLEX}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/backend-protocol: "http"
        hosts:
        - host: plex.${CLUSTER_DOMAIN}
          paths:
          - path: /
            service:
              name: plex
              port: 32400
        tls:
        - secretName: plex-tls
          hosts:
          - plex.${CLUSTER_DOMAIN}
    persistence:
      tmp:
        enabled: true
        hostPath: /plex/tmp
        type: hostPath
        globalMounts:
        - path: /tmp
          readOnly: false
      transcode:
        enabled: true
        hostPath: /plex/transcode
        type: hostPath
        globalMounts:
        - path: /transcode
          readOnly: false
      config:
        enabled: true
        hostPath: /plex/config
        type: hostPath
        globalMounts:
        - path: /config
          readOnly: false
      tv:
        enabled: true
        hostPath: /tv
        type: hostPath
        globalMounts:
        - path: /tv
          readOnly: true
      movies:
        enabled: true
        hostPath: /movies
        type: hostPath
        globalMounts:
        - path: /movies
          readOnly: true
      misc:
        enabled: true
        hostPath: /tank0/misc
        type: hostPath
        globalMounts:
        - path: /misc
          readOnly: true
