---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-coredns-config
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/coredns/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
