---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-path
  postgresql:
    shared_preload_libraries:
    - vectors.so
    - vchord.so
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
      - CREATE EXTENSION IF NOT EXISTS vectors;
      - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
      - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
      - ALTER SCHEMA vectors OWNER TO immich;
      - GRANT ALL ON SCHEMA vectors TO immich;
