---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-vars
  namespace: flux-system
spec:
  path: ./cluster/flux/vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  retryInterval: 1m
  timeout: 5m
