---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ori-edge.github.io/k8s_gateway/
      chart: k8s-gateway
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  maxHistory: 3
  values:
    domain: ${CLUSTER_DOMAIN}
    service:
      type: LoadBalancer
      loadBalancerIP: "${K8S_GATEWAY}"
      externalTrafficPolicy: Local
