---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 2h
  type: oci
  url: oci://ghcr.io/k8s-gateway/charts
  timeout: 2m
