---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
    namespace: flux-system
  maxHistory: 3
  values:
    domain: ${CLUSTER_DOMAIN}
    watchedResources:
    - HTTPRoute
    - Service
    filters:
      gatewayClasses:
      - eg
    service:
      type: ClusterIP
