---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  namespace: networking
  labels:
    app: speedtest-exporter
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  endpoints:
  - port: metrics
    interval: 1h
    scrapeTimeout: 90s
