---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: networking
  labels:
    app: speedtest-exporter
spec:
  selector:
    app: speedtest-exporter
  ports:
  - name: metrics
    port: 9798
    targetPort: metrics
