apiVersion: v1
kind: Secret
metadata:
    name: gato-bot-github-app
    namespace: actions
stringData:
    github_app_id: ENC[AES256_GCM,data:20cjISxX,iv:daEoPQq/HIPKqnhQG+fFn9CQs8OOx20nkp4Qj/PBmrk=,tag:JmU6c1i49nX+DH+JayTJ8Q==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:6AOnCgLJMfHSog==,iv:/ZjjnxURx9QMF9zytWPCwApbBu2Yyv1/345cNEiPflo=,tag:mZ4uK+QojhU4uvel0opTXg==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:aZJ8uBil3Ps39prMjPqz37ar9Oi6HNRbvWONZCBPllGnXHlQAo4okfXbhstZjLPT5WREYPRTlLRj7RZ1NCkQ3jRbdjxiaMK1hygMMNIHl6iuuJlNaOykMkPSauxqwNc=,iv:JOv0IlTrGqXRTJzNQ1G687mvdzeQKp5B+7dQKjEBnZA=,tag:LUTxuA2qUu1bCsIcpHSwMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1lmclc0RWxudTA4RVdx
            MUgzaTlRbEVCcWhBekdGeWp1bVd3aVByS3hBCng4alhabnhYRXZOaXA1cmFVR0Fz
            eFcxWElVWC9mUndJZndyTzl2KzVHbkUKLS0tIHpFZUtSL3dBd29uaTdTdTl0T0FZ
            czVSSmwxaGpBQmFpellScDQ2bjE5NVEKP77MH6kl14Vn/nRG/X0guOKt/nLI7FqV
            dVY8Uk8K1ST9IQMPP6jYq54hgxMhmG4ef88oXfZQQT4NgZHcTiJo2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
    encrypted_regex: ^(data|stringData|acme)$
    lastmodified: "2026-09-06T03:32:54Z"
    mac: ENC[AES256_GCM,data:f7b0RIizdbKBcXui0CBwSiinpWHSePUf4ADt9qrwwHTk8Hu62p30Gg3d4CEIRRIJWT8oRIEXACbJUdSC0Gh1ApEmlSLDb1M6jZMcSepF3HftOlzR2sEMVr+YTcUyGDLV98xn6zSMM/DGzM+UUBcfetCTRhWp6SQJmPPBSxuhUTA=,iv:GfC3Oh/Z49+DiqD3zIzo7SeBP5oDBadwJzfBVBg8Gb8=,tag:Uv2pVcilyGwBARKhmF3JmA==,type:str]
    version: 3.13.3
