---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  values:
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: false
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${BLOCKY}"
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    controller:
      replicas: 1
    metrics:
      enabled: false
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    config: |
      upstream:
        default:
          - 1.1.1.1
          - 1.0.0.1
      conditional:
        mapping:
          ${CLUSTER_DOMAIN}: ${K8S_GATEWAY}
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://dbl.oisd.nl/
        clientGroupsBlock:
          default:
            - ads
      port: 53
      httpPort: 4000
