---
apiVersion: v1
kind: Service
metadata:
  name: blocky-metrics
  namespace: networking
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    protocol: TCP
