---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  maxHistory: 3
  values:
    crds:
      enabled: true
    prometheus:
      namespace: monitoring
      serviceAccount: kube-prometheus-stack-prometheus
      podMonitor:
        enabled: true
    speaker:
      tolerateMaster: true
