apiVersion: v1
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:DUbNR+//o1I=,iv:23RpRVf33jARmEv8Pyb2oQE+6IKJ5OepPY76BUDzmlk=,tag:YF3VpFKk4dcno7RGyot5VQ==,type:str]
    K8S_GATEWAY: ENC[AES256_GCM,data:sbH3mH5Q4cCJewKc,iv:RpVU3ZBFRkpfqG7CtRraUGGpP/XknFA1TP2HNjb3DtE=,tag:59NzBxxRw00XS0r4UbLbcQ==,type:str]
    PLEX: ENC[AES256_GCM,data:DqCPR8vg1onM/gYf,iv:2nhTWriuigUjEW5b9w5jBk33w5FYhRGxc4jReH5KZ6o=,tag:667wsygMXF5gO3sRammfgw==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:opvpgTXKiKK1f49NfF23JtF/PfTBSwCpqNE=,iv:YXMWhx4s+3vfjK5fXVCpT82VLhAdd+8Fx/UWQ9uiaf8=,tag:R0JhmNna8YNcGmh4k7KE9Q==,type:str]
    BLOCKY: ENC[AES256_GCM,data:9/cYNVYdKOjDnqdp,iv:AAnt2xsouv3xiY2tN+RhE4cL2PAvDPcq+ImHW/923aU=,tag:gZsywc26tj4wqn0R+vAyLQ==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVG1QTVdodmpaMzJKNU5G
            NGd3VDZDOThUeGNZSmZxaTcyYitYSldEb25RCktGZHpobVVKVlcvcHpEUEtkaVZk
            RVYveXl6ejYrZXM2eTh2VnU0anEwMmcKLS0tIG9ScjRQSEdsQkl0S3FMTjBtd0ZT
            SGRxYS83QlJINXJmaCtnU0N5ZGtYTEUKy/Hji6HJJLkzq+J+xzJ9m6fcAbnvJ5DQ
            XMUCoqmHZUW2nulI/Hw44oqkSlqHmsHllA3yEDNLD40JjunkyIrIfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:57:22Z"
    mac: ENC[AES256_GCM,data:fsYNH/7Ckz+EbxWeYKDSlFNlK9800Rs0eEtk/LX3ZUztO8YPSN8GUIuOMkk6EWRPpb9S3mnIYJ3KhM+QZBQhuqWr3G+Pkp/snj1cNDkRJIn26fuyKzMAAUrwBVMK2SywovPiOmM0E4Obd2MKiI5KCY/a7KwMB5Hfi1OtKsmeNjQ=,iv:GsSI58+0DMLppvzGpj73JaxIjvYuf7heuejan3M3ipY=,tag:Fitj+GM+s2gO9ri2Xr8P8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
