---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: lab.internal
  ENVOY_GATEWAY: 10.0.201.200
  BLOCKY: 10.0.201.201
  PLEX: 10.0.201.202
