apiVersion: v1
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:9olaVf9X,iv:DigSgF5E8rJSYqEqwrxyYiEMIr5P1Ii+WqvP2xDCU9M=,tag:SOkUYLXP15I5vQ7yxclM6Q==,type:str]
    INGRESS_NGINX: ENC[AES256_GCM,data:jTVmWwoldoye9t7K,iv:TbmyRtxQS5U1Iuf7DFHahuneglHC9aUxII1cKrrpXnQ=,tag:aqS1CzVH5N3Ho/u7Iu/cXg==,type:str]
    K8S_GATEWAY: ENC[AES256_GCM,data:GBdKAJAflDRzryOs,iv:azdVscn94v6svJLsBwVoZUqx7sJKJUpPI+MpqyfhcrY=,tag:AoKuUvN3vI8/FcvjIC/pOw==,type:str]
    PLEX: ENC[AES256_GCM,data:AU1xX+83Coe3r4t0,iv:U3wo7gmZCzcmB57YmOSCrgdVu/cdthOyaxe113SaKvQ=,tag:SkSsSP/wLj+aM7caGepTTA==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:SaywlqsSDOc2dEo5stSuyWLvL655p9MTImI=,iv:2i0VdkkXLHW5H9QCQO/M1ssqhcDw09rI+pz276G6yzs=,tag:Ej0fsJpxGhPNrRHyFCQxMQ==,type:str]
    BLOCKY: ENC[AES256_GCM,data:Cks+5PO+XlsHKss=,iv:9KNWGWlO1X5m7kl/1aTIgsS2y+oTL+nqY6JsYByNJQc=,tag:QLQb6cJ9CiAo382sftR8WA==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVG1QTVdodmpaMzJKNU5G
            NGd3VDZDOThUeGNZSmZxaTcyYitYSldEb25RCktGZHpobVVKVlcvcHpEUEtkaVZk
            RVYveXl6ejYrZXM2eTh2VnU0anEwMmcKLS0tIG9ScjRQSEdsQkl0S3FMTjBtd0ZT
            SGRxYS83QlJINXJmaCtnU0N5ZGtYTEUKy/Hji6HJJLkzq+J+xzJ9m6fcAbnvJ5DQ
            XMUCoqmHZUW2nulI/Hw44oqkSlqHmsHllA3yEDNLD40JjunkyIrIfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T22:29:22Z"
    mac: ENC[AES256_GCM,data:tOkiRaF5OoJ1QDeEN/PuDKf7/iwUDfU4BsSC+tOXw7C9UJV3Cw/hPMzzjIKCPy6/LaNurZw2+Ff4LTqTI+0Fh88AxxZOrbxYbY7v6ukyhw8Ym7o7ORlhs71Do3pDddVzLR+AS37E01kBQb77TgqpamOR3XEBuCsM04GyW9r4hXI=,iv:jqgwrpWW95YwXXOGjwSnaoS+itTnva6UxWIT2GeDsvE=,tag:c2RNQJSn/tEjZveX8P+Qng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
