apiVersion: v1
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:9olaVf9X,iv:DigSgF5E8rJSYqEqwrxyYiEMIr5P1Ii+WqvP2xDCU9M=,tag:SOkUYLXP15I5vQ7yxclM6Q==,type:str]
    INGRESS_NGINX: ENC[AES256_GCM,data:DCh1W0hppN/0LEw7,iv:y/vlrBeJHUF5FYsFrdUAifYu+Mpd7SvyRjmwuWpN5+M=,tag:0sPHzRZgiVpWQvIzxL1GbQ==,type:str]
    K8S_GATEWAY: ENC[AES256_GCM,data:sbH3mH5Q4cCJewKc,iv:RpVU3ZBFRkpfqG7CtRraUGGpP/XknFA1TP2HNjb3DtE=,tag:59NzBxxRw00XS0r4UbLbcQ==,type:str]
    PLEX: ENC[AES256_GCM,data:DqCPR8vg1onM/gYf,iv:2nhTWriuigUjEW5b9w5jBk33w5FYhRGxc4jReH5KZ6o=,tag:667wsygMXF5gO3sRammfgw==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:opvpgTXKiKK1f49NfF23JtF/PfTBSwCpqNE=,iv:YXMWhx4s+3vfjK5fXVCpT82VLhAdd+8Fx/UWQ9uiaf8=,tag:R0JhmNna8YNcGmh4k7KE9Q==,type:str]
    BLOCKY: ENC[AES256_GCM,data:9/cYNVYdKOjDnqdp,iv:AAnt2xsouv3xiY2tN+RhE4cL2PAvDPcq+ImHW/923aU=,tag:gZsywc26tj4wqn0R+vAyLQ==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVG1QTVdodmpaMzJKNU5G
            NGd3VDZDOThUeGNZSmZxaTcyYitYSldEb25RCktGZHpobVVKVlcvcHpEUEtkaVZk
            RVYveXl6ejYrZXM2eTh2VnU0anEwMmcKLS0tIG9ScjRQSEdsQkl0S3FMTjBtd0ZT
            SGRxYS83QlJINXJmaCtnU0N5ZGtYTEUKy/Hji6HJJLkzq+J+xzJ9m6fcAbnvJ5DQ
            XMUCoqmHZUW2nulI/Hw44oqkSlqHmsHllA3yEDNLD40JjunkyIrIfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T04:24:57Z"
    mac: ENC[AES256_GCM,data:OI4Yk+Eh4wkLsQQPIVftpMfWbApQjgVpI8v9zZ/EBNI7hc0GetpqgjmHTqtv21Q5mftFhiCjyDgMtX/OWVTjJe+niyDKfgSl5yUHkLzyGz+PvJbpVUnrc4dn6InbzwcNI7yjsMUGMXJ4vU2lYBxUnkcFjhlGohhFf75QeUXvIOo=,iv:lI8SxKRBPJN+20EklNYeU+VrOEtIVlMC8MA0cP2fxuo=,tag:ft6PrY8NZBQ82oYGm+Yy+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
