apiVersion: v1
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:H6/HEzNq5OKQyHRkhpIpsoL0/CN5Q8tafWA=,iv:lo6L89aFyRq/y45ahAfKMdPx5BtTnSULZyNiXMVRpjU=,tag:Upk4i9NDwuMKYZvi8fKbkQ==,type:str]
kind: Secret
metadata:
    name: plex-vars
    namespace: flux-system
sops:
    age:
        - recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYkFrZ2RGY09USzVvQ1B2
            VUZCcDlLZlpsdC9pTTVub2FVaXdobzJuRTM0CjZ6SzV2Z2NTaDFkTnkyNXl4NlNl
            NFB4dzZyRkZwOE92OGVIZlo0M0NKL00KLS0tIHNEQzNZc2JTaXFnNm1ibk0wbzJ4
            T2d0aFhYWmpFTElDeXVuVjhvdDBvNTgKMJGMiTbsmn2+8L42rGx7SwcwWlp0cJc4
            cRT7n88yyiqv+So40qxFWIprtzUk31RLnS2a+5+TzCR2qs7+RTXBJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T14:20:25Z"
    mac: ENC[AES256_GCM,data:Wl7OGTGaoziJ9duPaogWuwFUVFBtz4cx8WtOysbrEJuA9XiycPDjRDxPfTs66Khm9iKPCkKttr4iOMLLeQAcZrb8t7lZtfMXGZ6/CadzeZbVLrzrTbHVxCQ9xt+VvPvTnr8XVTLvRzZUgT322srsdoARl47sAZGVzY84HkOJwag=,iv:/h3zPiLkbJmFuIRPfV7nEIwJ4zZYxZkMnVR4TazOyLo=,tag:EzNBdwFrWCa+uDuTazx90g==,type:str]
    encrypted_regex: ^(data|stringData|acme)$
    version: 3.12.1
