apiVersion: v1
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:7xCABhzEKkSaVxfCwWDDVl0Pw/haVwSRwnw=,iv:INfVO7NeTQrHrGvsAdcOPWL+B4Lbq9tEKH5Box0azr4=,tag:Hv7xdxqr8nYF3B9k3aS6hg==,type:str]
kind: Secret
metadata:
    name: plex-vars
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYkFrZ2RGY09USzVvQ1B2
            VUZCcDlLZlpsdC9pTTVub2FVaXdobzJuRTM0CjZ6SzV2Z2NTaDFkTnkyNXl4NlNl
            NFB4dzZyRkZwOE92OGVIZlo0M0NKL00KLS0tIHNEQzNZc2JTaXFnNm1ibk0wbzJ4
            T2d0aFhYWmpFTElDeXVuVjhvdDBvNTgKMJGMiTbsmn2+8L42rGx7SwcwWlp0cJc4
            cRT7n88yyiqv+So40qxFWIprtzUk31RLnS2a+5+TzCR2qs7+RTXBJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rchcs2gk3wa0h8hdsvm3enu7qa4yq9gmag9k32qsfvrgghgufq2smx4s3n
    encrypted_regex: ^(data|stringData|acme)$
    lastmodified: "2026-06-14T05:37:44Z"
    mac: ENC[AES256_GCM,data:lTP/suHLdNLKmx+zSrYFnDWtpAH3xUAgVmUzkm1CskCgWnQYHk6fr1XSNVPQC/te5Y6megCeXUdQKDnMU5Fj9bBXsO2N2bF4aKP8JChCSmWrVtmWhaInmqE27+4tE4UybGIlS8N9t4PUtdxGNhd3MNuV9V9ZzEfmPLsTmKgkhoQ=,iv:bT+o9wpKL3F04ukQ9zHW+Idvy6jwCzYucsoOS3tcuig=,tag:wI7/sNlO89KzwqU3I4ahfg==,type:str]
    version: 3.12.1
