---
name: Renovate
on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 12 * * 1-5'

env:
  RENOVATE_REPOSITORIES: "${{ github.repository }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_SECRET }}
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@a447f09147d00e00ae2a82ad5ef51ca89352da80 # v43.0.9
      with:
        configurationFile: .github/renovate.json5
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: 'debug'
