---
name: Renovate
on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 12 * * 1-5'

env:
  RENOVATE_REPOSITORIES: "${{ github.repository }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_SECRET }}
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@8ac70de2fe55752c573155866e30735411e3b61c # v41.0.22
      with:
        configurationFile: .github/renovate.json5
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: 'debug'
