---
name: Renovate
on:
  push:
    branches:
    - main
  schedule:
  - cron: '* */2 * * 1-5'

env:
  RENOVATE_REPOSITORIES: "${{ github.repository }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_SECRET }}
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@8ce0fe8066eb6b16e1bf499b21bc96e5ccd962a4 # v40.2.3
      with:
        configurationFile: .github/renovate.json5
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: 'debug'
