---
name: Renovate
on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 12 * * 1-5'

env:
  RENOVATE_REPOSITORIES: "${{ github.repository }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_SECRET }}
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@a889a8abcb11ef7feaafaf5e483ea01d4bf7774e # v43.0.5
      with:
        configurationFile: .github/renovate.json5
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: 'debug'
